export { default as Message } from './Message.vue'
export { default as MessageContent } from './MessageContent.vue'
export { default as MessageActions } from './MessageActions.vue'
export { default as MessageAction } from './MessageAction.vue'
export { default as MessageAttachments } from './MessageAttachments.vue'
