export type TokenType = 'color' | 'size' | 'duration' | 'font' | 'text'
export type TokenLayer = 'primitive' | 'semantic' | 'component'

export interface TokenMeta {
  /** CSS 变量名，如 '--ai-chat-color-accent' */
  key: string
  layer: TokenLayer
  /** 分组名（中文），用于配置器折叠分组 */
  group: string
  /** 人类可读标签（中文） */
  label: string
  type: TokenType
  /** 亮色（:root）默认值；可能是 hex、var()、rgba、带单位的尺寸等 */
  light: string
  /** 暗色默认值；仅语义层需要、且与亮色不同时给出。缺省=暗色不覆盖 */
  dark?: string
  /** true=var() 引用，配置器中只读，显示解析色 + ref */
  derived?: boolean
  /** derived 时指向的原始令牌 key（仅展示用） */
  ref?: string
  /** size/duration 的单位提示 */
  unit?: 'px' | 's'
  /** size/duration 滑块范围 */
  min?: number
  max?: number
}

export const tokensMeta: TokenMeta[] = [
  // ===== 原始·主色色阶 =====
  {
    key: '--ai-chat-color-accent-500',
    layer: 'primitive',
    group: '原始·主色色阶',
    label: '主色 500',
    type: 'color',
    light: '#6366f1',
  },
  {
    key: '--ai-chat-color-accent-600',
    layer: 'primitive',
    group: '原始·主色色阶',
    label: '主色 600',
    type: 'color',
    light: '#4f46e5',
  },
  {
    key: '--ai-chat-color-accent-400',
    layer: 'primitive',
    group: '原始·主色色阶',
    label: '主色 400',
    type: 'color',
    light: '#818cf8',
  },

  // ===== 原始·中性灰阶 =====
  {
    key: '--ai-chat-neutral-0',
    layer: 'primitive',
    group: '原始·中性灰阶',
    label: '中性 0',
    type: 'color',
    light: '#ffffff',
  },
  {
    key: '--ai-chat-neutral-50',
    layer: 'primitive',
    group: '原始·中性灰阶',
    label: '中性 50',
    type: 'color',
    light: '#f9fafb',
  },
  {
    key: '--ai-chat-neutral-100',
    layer: 'primitive',
    group: '原始·中性灰阶',
    label: '中性 100',
    type: 'color',
    light: '#f3f4f6',
  },
  {
    key: '--ai-chat-neutral-200',
    layer: 'primitive',
    group: '原始·中性灰阶',
    label: '中性 200',
    type: 'color',
    light: '#e5e7eb',
  },
  {
    key: '--ai-chat-neutral-300',
    layer: 'primitive',
    group: '原始·中性灰阶',
    label: '中性 300',
    type: 'color',
    light: '#d1d5db',
  },
  {
    key: '--ai-chat-neutral-500',
    layer: 'primitive',
    group: '原始·中性灰阶',
    label: '中性 500',
    type: 'color',
    light: '#6b7280',
  },
  {
    key: '--ai-chat-neutral-600',
    layer: 'primitive',
    group: '原始·中性灰阶',
    label: '中性 600',
    type: 'color',
    light: '#4b5563',
  },
  {
    key: '--ai-chat-neutral-700',
    layer: 'primitive',
    group: '原始·中性灰阶',
    label: '中性 700',
    type: 'color',
    light: '#404040',
  },
  {
    key: '--ai-chat-neutral-800',
    layer: 'primitive',
    group: '原始·中性灰阶',
    label: '中性 800',
    type: 'color',
    light: '#262626',
  },
  {
    key: '--ai-chat-neutral-900',
    layer: 'primitive',
    group: '原始·中性灰阶',
    label: '中性 900',
    type: 'color',
    light: '#171717',
  },
  {
    key: '--ai-chat-neutral-950',
    layer: 'primitive',
    group: '原始·中性灰阶',
    label: '中性 950',
    type: 'color',
    light: '#0a0a0a',
  },

  // ===== 原始·功能色 =====
  {
    key: '--ai-chat-color-danger-500',
    layer: 'primitive',
    group: '原始·功能色',
    label: '危险 500',
    type: 'color',
    light: '#ef4444',
  },

  // ===== 原始·圆角 =====
  {
    key: '--ai-chat-radius-sm',
    layer: 'primitive',
    group: '原始·圆角',
    label: '圆角 sm',
    type: 'size',
    light: '6px',
    unit: 'px',
    min: 0,
    max: 24,
  },
  {
    key: '--ai-chat-radius-md',
    layer: 'primitive',
    group: '原始·圆角',
    label: '圆角 md',
    type: 'size',
    light: '8px',
    unit: 'px',
    min: 0,
    max: 24,
  },
  {
    key: '--ai-chat-radius-lg',
    layer: 'primitive',
    group: '原始·圆角',
    label: '圆角 lg',
    type: 'size',
    light: '12px',
    unit: 'px',
    min: 0,
    max: 32,
  },
  {
    key: '--ai-chat-radius-xl',
    layer: 'primitive',
    group: '原始·圆角',
    label: '圆角 xl',
    type: 'size',
    light: '16px',
    unit: 'px',
    min: 0,
    max: 40,
  },

  // ===== 原始·字体 =====
  {
    key: '--ai-chat-font-sans',
    layer: 'primitive',
    group: '原始·字体',
    label: '正文字体',
    type: 'font',
    light: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  },
  {
    key: '--ai-chat-font-mono',
    layer: 'primitive',
    group: '原始·字体',
    label: '等宽字体',
    type: 'font',
    light: "'SF Mono', 'Fira Code', 'Consolas', monospace",
  },

  // ===== 原始·动画 =====
  {
    key: '--ai-chat-duration-fast',
    layer: 'primitive',
    group: '原始·动画',
    label: '动画 快',
    type: 'duration',
    light: '0.12s',
    unit: 's',
    min: 0,
    max: 1,
  },
  {
    key: '--ai-chat-duration-normal',
    layer: 'primitive',
    group: '原始·动画',
    label: '动画 常规',
    type: 'duration',
    light: '0.2s',
    unit: 's',
    min: 0,
    max: 1,
  },
  {
    key: '--ai-chat-easing',
    layer: 'primitive',
    group: '原始·动画',
    label: '缓动函数',
    type: 'text',
    light: 'ease',
  },

  // ===== 原始·尺寸 =====
  {
    key: '--ai-chat-sidebar-width',
    layer: 'primitive',
    group: '原始·尺寸',
    label: '侧边栏宽',
    type: 'size',
    light: '260px',
    unit: 'px',
    min: 200,
    max: 400,
  },
  {
    key: '--ai-chat-content-max-width',
    layer: 'primitive',
    group: '原始·尺寸',
    label: '内容最大宽',
    type: 'size',
    light: '768px',
    unit: 'px',
    min: 480,
    max: 1200,
  },
  {
    key: '--ai-chat-input-max-height',
    layer: 'primitive',
    group: '原始·尺寸',
    label: '输入框最大高',
    type: 'size',
    light: '200px',
    unit: 'px',
    min: 80,
    max: 600,
  },
  {
    key: '--ai-chat-avatar-size',
    layer: 'primitive',
    group: '原始·尺寸',
    label: '头像大小',
    type: 'size',
    light: '30px',
    unit: 'px',
    min: 20,
    max: 64,
  },
  {
    key: '--ai-chat-btn-icon-size',
    layer: 'primitive',
    group: '原始·尺寸',
    label: '图标按钮',
    type: 'size',
    light: '36px',
    unit: 'px',
    min: 24,
    max: 56,
  },
  {
    key: '--ai-chat-btn-tool-size',
    layer: 'primitive',
    group: '原始·尺寸',
    label: '工具按钮',
    type: 'size',
    light: '32px',
    unit: 'px',
    min: 20,
    max: 48,
  },
  {
    key: '--ai-chat-msg-gap',
    layer: 'primitive',
    group: '原始·尺寸',
    label: '消息间距',
    type: 'size',
    light: '16px',
    unit: 'px',
    min: 0,
    max: 48,
  },
  {
    key: '--ai-chat-msg-padding-y',
    layer: 'primitive',
    group: '原始·尺寸',
    label: '消息纵向内边距',
    type: 'size',
    light: '20px',
    unit: 'px',
    min: 0,
    max: 48,
  },
  {
    key: '--ai-chat-content-max-width-wide',
    layer: 'primitive',
    group: '原始·尺寸',
    label: '宽屏内容最大宽',
    type: 'size',
    light: '1024px',
    unit: 'px',
    min: 768,
    max: 1600,
  },
  {
    key: '--ai-chat-message-max-width',
    layer: 'primitive',
    group: '原始·尺寸',
    label: '消息气泡最大宽',
    type: 'size',
    light: '480px',
    unit: 'px',
    min: 240,
    max: 960,
  },
  {
    key: '--ai-chat-input-max-height-mobile',
    layer: 'primitive',
    group: '原始·尺寸',
    label: '移动端输入框最大高',
    type: 'size',
    light: '120px',
    unit: 'px',
    min: 60,
    max: 240,
  },

  // ===== 原始·断点 =====
  {
    key: '--ai-chat-mobile-breakpoint',
    layer: 'primitive',
    group: '原始·断点',
    label: '移动端断点',
    type: 'size',
    light: '640px',
    unit: 'px',
    min: 320,
    max: 1024,
  },

  // ===== 语义·强调 =====
  {
    key: '--ai-chat-color-accent',
    layer: 'semantic',
    group: '语义·强调',
    label: '主色',
    type: 'color',
    light: 'var(--ai-chat-color-accent-500)',
    derived: true,
    ref: '--ai-chat-color-accent-500',
  },
  {
    key: '--ai-chat-color-accent-hover',
    layer: 'semantic',
    group: '语义·强调',
    label: '主色 hover',
    type: 'color',
    light: 'var(--ai-chat-color-accent-400)',
    derived: true,
    ref: '--ai-chat-color-accent-400',
  },
  {
    key: '--ai-chat-color-accent-dim',
    layer: 'semantic',
    group: '语义·强调',
    label: '主色淡底',
    type: 'text',
    light: 'rgba(99, 102, 241, 0.15)',
    dark: 'rgba(99, 102, 241, 0.2)',
  },

  // ===== 语义·背景 =====
  {
    key: '--ai-chat-color-bg-primary',
    layer: 'semantic',
    group: '语义·背景',
    label: '主背景',
    type: 'color',
    light: 'var(--ai-chat-neutral-0)',
    dark: 'var(--ai-chat-neutral-900)',
    derived: true,
    ref: '中性阶',
  },
  {
    key: '--ai-chat-color-bg-secondary',
    layer: 'semantic',
    group: '语义·背景',
    label: '次背景',
    type: 'color',
    light: 'var(--ai-chat-neutral-50)',
    dark: 'var(--ai-chat-neutral-800)',
    derived: true,
    ref: '中性阶',
  },
  {
    key: '--ai-chat-color-bg-chat',
    layer: 'semantic',
    group: '语义·背景',
    label: '聊天区背景',
    type: 'color',
    light: 'var(--ai-chat-neutral-0)',
    dark: 'var(--ai-chat-neutral-900)',
    derived: true,
    ref: '中性阶',
  },
  {
    key: '--ai-chat-color-bg-sidebar',
    layer: 'semantic',
    group: '语义·背景',
    label: '侧边栏背景',
    type: 'color',
    light: 'var(--ai-chat-neutral-50)',
    dark: 'var(--ai-chat-neutral-900)',
    derived: true,
    ref: '中性阶',
  },
  {
    key: '--ai-chat-color-bg-sidebar-hover',
    layer: 'semantic',
    group: '语义·背景',
    label: '侧边栏悬停',
    type: 'color',
    light: 'var(--ai-chat-neutral-100)',
    dark: 'var(--ai-chat-neutral-800)',
    derived: true,
    ref: '中性阶',
  },
  {
    key: '--ai-chat-color-bg-sidebar-active',
    layer: 'semantic',
    group: '语义·背景',
    label: '侧边栏选中',
    type: 'color',
    light: 'var(--ai-chat-neutral-200)',
    dark: '#2a2a2a',
  },

  // ===== 语义·文本 =====
  {
    key: '--ai-chat-color-text-primary',
    layer: 'semantic',
    group: '语义·文本',
    label: '主文本',
    type: 'color',
    light: 'var(--ai-chat-neutral-900)',
    dark: 'var(--ai-chat-neutral-50)',
    derived: true,
    ref: '中性阶',
  },
  {
    key: '--ai-chat-color-text-secondary',
    layer: 'semantic',
    group: '语义·文本',
    label: '次文本',
    type: 'color',
    light: 'var(--ai-chat-neutral-600)',
    dark: '#a1a1aa',
  },
  {
    key: '--ai-chat-color-text-muted',
    layer: 'semantic',
    group: '语义·文本',
    label: '弱文本',
    type: 'color',
    light: '#9ca3af',
    dark: '#71717a',
  },
  {
    key: '--ai-chat-color-sidebar-text',
    layer: 'semantic',
    group: '语义·文本',
    label: '侧边栏文本',
    type: 'color',
    light: 'var(--ai-chat-neutral-500)',
    dark: '#a1a1aa',
  },
  {
    key: '--ai-chat-color-sidebar-text-active',
    layer: 'semantic',
    group: '语义·文本',
    label: '侧边栏选中文本',
    type: 'color',
    light: 'var(--ai-chat-neutral-900)',
    dark: 'var(--ai-chat-neutral-50)',
    derived: true,
    ref: '中性阶',
  },

  // ===== 语义·边框/滚动条 =====
  {
    key: '--ai-chat-color-border',
    layer: 'semantic',
    group: '语义·边框',
    label: '边框',
    type: 'color',
    light: 'var(--ai-chat-neutral-200)',
    dark: '#2e2e2e',
  },
  {
    key: '--ai-chat-color-sidebar-border',
    layer: 'semantic',
    group: '语义·边框',
    label: '侧边栏边框',
    type: 'color',
    light: 'var(--ai-chat-neutral-200)',
    dark: '#2e2e2e',
  },
  {
    key: '--ai-chat-scrollbar-thumb',
    layer: 'semantic',
    group: '语义·边框',
    label: '滚动条拇指',
    type: 'color',
    light: 'var(--ai-chat-neutral-300)',
    dark: 'var(--ai-chat-neutral-700)',
    derived: true,
    ref: '中性阶',
  },
  {
    key: '--ai-chat-scrollbar-track',
    layer: 'semantic',
    group: '语义·边框',
    label: '滚动条轨道',
    type: 'text',
    light: 'transparent',
  },

  // ===== 语义·输入 =====
  {
    key: '--ai-chat-color-input-bg',
    layer: 'semantic',
    group: '语义·输入',
    label: '输入框背景',
    type: 'color',
    light: 'var(--ai-chat-neutral-100)',
    dark: '#2f2f2f',
  },
  {
    key: '--ai-chat-color-input-border',
    layer: 'semantic',
    group: '语义·输入',
    label: '输入框边框',
    type: 'color',
    light: 'var(--ai-chat-neutral-300)',
    dark: 'var(--ai-chat-neutral-700)',
    derived: true,
    ref: '中性阶',
  },
  {
    key: '--ai-chat-color-input-focus-border',
    layer: 'semantic',
    group: '语义·输入',
    label: '输入框聚焦边框',
    type: 'color',
    light: 'var(--ai-chat-color-accent-500)',
    derived: true,
    ref: '--ai-chat-color-accent-500',
  },

  // ===== 语义·消息 =====
  {
    key: '--ai-chat-color-msg-user-bg',
    layer: 'semantic',
    group: '语义·消息',
    label: '用户消息背景',
    type: 'color',
    light: 'var(--ai-chat-neutral-100)',
    dark: '#2f2f2f',
  },
  {
    key: '--ai-chat-color-msg-assistant-bg',
    layer: 'semantic',
    group: '语义·消息',
    label: 'AI 消息背景',
    type: 'text',
    light: 'transparent',
  },

  // ===== 语义·代码 =====
  {
    key: '--ai-chat-color-code-bg',
    layer: 'semantic',
    group: '语义·代码',
    label: '代码块背景',
    type: 'color',
    light: 'var(--ai-chat-neutral-100)',
    dark: 'var(--ai-chat-neutral-800)',
    derived: true,
    ref: '中性阶',
  },
  {
    key: '--ai-chat-color-code-header-bg',
    layer: 'semantic',
    group: '语义·代码',
    label: '代码块头背景',
    type: 'color',
    light: 'var(--ai-chat-neutral-100)',
    dark: '#242427',
  },
  {
    key: '--ai-chat-color-code-inline-bg',
    layer: 'semantic',
    group: '语义·代码',
    label: '行内代码背景',
    type: 'text',
    light: 'rgba(0, 0, 0, 0.06)',
    dark: 'rgba(255, 255, 255, 0.06)',
  },

  // ===== 语义·状态 =====
  {
    key: '--ai-chat-color-status-error',
    layer: 'semantic',
    group: '语义·状态',
    label: '错误',
    type: 'color',
    light: '#ef4444',
    dark: '#f87171',
  },
  {
    key: '--ai-chat-color-status-warning',
    layer: 'semantic',
    group: '语义·状态',
    label: '警告',
    type: 'color',
    light: '#f59e0b',
    dark: '#fbbf24',
  },
  {
    key: '--ai-chat-color-status-success',
    layer: 'semantic',
    group: '语义·状态',
    label: '成功',
    type: 'color',
    light: '#10b981',
    dark: '#34d399',
  },

  // ===== 语义·交互 =====
  {
    key: '--ai-chat-hover-neutral',
    layer: 'semantic',
    group: '语义·交互',
    label: '中性悬停',
    type: 'text',
    light: 'rgba(128, 128, 128, 0.15)',
  },

  // ===== 组件 =====
  {
    key: '--ai-chat-bubble-radius',
    layer: 'component',
    group: '组件·消息',
    label: '气泡圆角',
    type: 'color',
    light: 'var(--ai-chat-radius-lg)',
    derived: true,
    ref: '--ai-chat-radius-lg',
  },
]
