import { describe, it, expect } from 'vitest'
import { buildThemeCss, buildOverridesFromCss } from './theme-css'
// 直接走源码相对路径：root vitest 配置未声明 @toimc/* 别名
import { tokensMeta } from '../../../vue/src'
import type { TokenMeta } from '../../../vue/src'

// 取一条真实令牌做单点改动，避免硬编码字符串与 spec 默认值脱钩
const accent500 = tokensMeta.find(
  (t) => t.key === '--ai-chat-color-accent-500',
)! as TokenMeta
const statusError = tokensMeta.find(
  (t) => t.key === '--ai-chat-color-status-error',
)! as TokenMeta

const MINI_META: TokenMeta[] = [
  accent500,
  statusError,
  // 一个无 dark 值的令牌，覆盖 curDark === undefined 分支
  tokensMeta.find((t) => t.key === '--ai-chat-radius-sm')! as TokenMeta,
]

describe('buildThemeCss', () => {
  it('includeAll=false 时仅导出改动过的令牌', () => {
    const overrides = {
      '--ai-chat-color-accent-500': { light: '#ff0000' },
    }
    const css = buildThemeCss(MINI_META, overrides, { includeAll: false })
    expect(css).toContain('--ai-chat-color-accent-500: #ff0000;')
    // 未改动的令牌不出现在输出里
    expect(css).not.toContain('--ai-chat-color-status-error')
    expect(css).not.toContain('--ai-chat-radius-sm')
    // 必有 :root 块
    expect(css).toMatch(/:root\s*\{/)
    // 不应有暗色块（无 dark 改动）
    expect(css).not.toMatch(/\[data-theme=['"]?dark['"]?\]/)
  })

  it('includeAll=true 时导出全部令牌（含未改动）', () => {
    const css = buildThemeCss(MINI_META, {}, { includeAll: true })
    expect(css).toContain('--ai-chat-color-accent-500:')
    expect(css).toContain('--ai-chat-color-status-error:')
    expect(css).toContain('--ai-chat-radius-sm:')
    // status-error 有 dark 值，应同时出现在两个块里
    expect(css).toMatch(/:root\s*\{[\s\S]*--ai-chat-color-status-error/)
    expect(css).toMatch(
      /\[data-theme=['"]?dark['"]?\]\s*\{[\s\S]*--ai-chat-color-status-error/,
    )
    // radius-sm 无 dark 值，整体不应出现在暗色块（暗色块仍存在，因 status-error 暗色不同）
    const darkBlock = css.match(
      /\[data-theme=['"]?dark['"]?\]\s*\{([\s\S]*?)\}/,
    )?.[1]
    expect(darkBlock).not.toContain('--ai-chat-radius-sm')
  })

  it('改动同时覆盖 light 与 dark 时生成两个块', () => {
    const overrides = {
      '--ai-chat-color-status-error': { light: '#aaaaaa', dark: '#bbbbbb' },
    }
    const css = buildThemeCss(MINI_META, overrides, { includeAll: false })
    expect(css).toMatch(/:root\s*\{[\s\S]*#aaaaaa[\s\S]*\}/)
    expect(css).toMatch(
      /\[data-theme=['"]?dark['"]?\]\s*\{[\s\S]*#bbbbbb[\s\S]*\}/,
    )
  })

  it('改动的暗色值与默认相同时不导出暗色块条目', () => {
    // status-error.dark = '#f87171'，给个相同值
    const sameDark = statusError.dark!
    const overrides = {
      '--ai-chat-color-status-error': { dark: sameDark },
    }
    const css = buildThemeCss(MINI_META, overrides, { includeAll: false })
    expect(css).not.toContain('--ai-chat-color-status-error')
  })

  it('空 overrides + includeAll=false 输出仅注释', () => {
    const css = buildThemeCss(MINI_META, {}, { includeAll: false })
    expect(css.trim()).toBe(
      '/* ai-chat-ui custom theme — generated by Theme Builder */',
    )
  })
})

describe('buildOverridesFromCss', () => {
  it('解析 :root 与 [data-theme=dark] 块', () => {
    const css = [
      '/* header */',
      ':root {',
      '  --ai-chat-color-accent-500: #abc123;',
      '}',
      "[data-theme='dark'] {",
      '  --ai-chat-color-status-error: #deadbe;',
      '}',
    ].join('\n')
    const ov = buildOverridesFromCss(css, MINI_META)
    expect(ov['--ai-chat-color-accent-500']?.light).toBe('#abc123')
    expect(ov['--ai-chat-color-status-error']?.dark).toBe('#deadbe')
  })

  it('未知变量名被丢弃', () => {
    const css = [
      ':root {',
      '  --ai-chat-unknown-foo: #fff;',
      '  --ai-chat-color-accent-500: #123456;',
      '}',
    ].join('\n')
    const ov = buildOverridesFromCss(css, MINI_META)
    expect(ov['--ai-chat-unknown-foo']).toBeUndefined()
    expect(ov['--ai-chat-color-accent-500']?.light).toBe('#123456')
  })

  it('buildThemeCss → buildOverridesFromCss 往返一致', () => {
    const original = {
      '--ai-chat-color-accent-500': { light: '#ff0000', dark: '#00ff00' },
      '--ai-chat-color-status-error': { light: '#abcdef' },
    }
    const css = buildThemeCss(MINI_META, original, { includeAll: false })
    const parsed = buildOverridesFromCss(css, MINI_META)
    // 往返后只保留被解析出的值；原 dark: #00ff00 对应令牌默认 light（accent-500 无 dark 默认）
    // 由于 buildThemeCss 只在 curDark !== undefined 时输出，#00ff00 会被写入 dark 块
    expect(parsed['--ai-chat-color-accent-500']?.light).toBe('#ff0000')
    expect(parsed['--ai-chat-color-accent-500']?.dark).toBe('#00ff00')
    expect(parsed['--ai-chat-color-status-error']?.light).toBe('#abcdef')
  })
})
