import type { TokenMeta } from '@ai-chat/vue'

export type Overrides = Record<string, { light?: string; dark?: string }>

/** 生成导出 CSS。includeAll=false 时仅导出与默认不同的令牌。 */
export function buildThemeCss(
  meta: TokenMeta[],
  overrides: Overrides,
  opts: { includeAll?: boolean } = {},
): string {
  const lightLines: string[] = []
  const darkLines: string[] = []
  for (const t of meta) {
    const ov = overrides[t.key]
    const curLight = ov?.light ?? t.light
    const curDark = ov?.dark ?? t.dark
    const lightChanged = ov?.light !== undefined && ov.light !== t.light
    const darkChanged =
      ov?.dark !== undefined && ov.dark !== (t.dark ?? t.light)
    if (opts.includeAll || lightChanged)
      lightLines.push(`  ${t.key}: ${curLight};`)
    if (curDark !== undefined && (opts.includeAll || darkChanged))
      darkLines.push(`  ${t.key}: ${curDark};`)
  }
  const blocks: string[] = [
    '/* ai-chat-ui custom theme — generated by Theme Builder */',
  ]
  if (lightLines.length) blocks.push(`:root {\n${lightLines.join('\n')}\n}`)
  if (darkLines.length)
    blocks.push(`[data-theme='dark'] {\n${darkLines.join('\n')}\n}`)
  return blocks.join('\n\n') + '\n'
}

/** 从导出的 CSS 文本解析回 overrides。 */
export function buildOverridesFromCss(
  css: string,
  meta: TokenMeta[],
): Overrides {
  const ov: Overrides = {}
  const known = new Set(meta.map((m) => m.key))
  const parse = (block: string, mode: 'light' | 'dark') => {
    // [\w-]+ 已含前导的 `--`，故直接用作 key（spec 原始实现会重复前缀）
    const re = /([\w-]+)\s*:\s*([^;]+);/g
    let m: RegExpExecArray | null
    while ((m = re.exec(block))) {
      const key = m[1].startsWith('--') ? m[1] : `--${m[1]}`
      if (!known.has(key)) continue
      ;(ov[key] ??= {})[mode] = m[2].trim()
    }
  }
  const root = css.match(/:root\s*\{([\s\S]*?)\}/)
  const dark = css.match(/\[data-theme=['"]?dark['"]?\]\s*\{([\s\S]*?)\}/)
  if (root) parse(root[1], 'light')
  if (dark) parse(dark[1], 'dark')
  return ov
}
